trigger:
- main

pool:
  name: 'Default'
  demands:
    - Agent.Name -equals IMGROOT

parameters:
- name: nexla_id
  displayName: Nexla ID
  type: string
  default: '$(NEXLA_SOURCE_ID)'

variables:
  System/Debug: true

steps:

# Step to install the Nexla wheel file
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "Installing wheel file"
      echo $(Build.SourcesDirectory)
      pip install nexla-3.2.3-py3-none-any.whl --break-system-packages
  displayName: 'Install Nexla Wheel File'
  continueOnError: false

# Step to find and print the installed location of Nexla
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Use pip show to find the installation path of nexla
      pip show nexla
  displayName: 'Find Nexla Installation Path'
  continueOnError: false

# Step to add Nexla to the PATH (adjust for Windows)
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Update PATH for Windows system (adjust according to your Python environment)
      export PATH=$PATH:/home/groot/.local/bin  # Adjust this based on where nexla is installed on your system
      echo "Updated PATH: $PATH"
      nexla --version
  displayName: 'Update PATH for Nexla'
  continueOnError: false

# Step to set API environment variables
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      export API_URL=https://dataops.nexla.io/nexla-api
      export API_KEY=19e760802abb425992b3b4481ba051b8
      echo "API_URL is: $API_URL"
      echo "API_KEY is: $API_KEY"
  displayName: 'Set Nexla API Environment Variables'
  continueOnError: false

# Step to run the Nexla command for exporting flows
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'nexla flows export --s 53711 -o 53711.json'
  displayName: 'Export Nexla Flows'
  continueOnError: false
