trigger:
- main

pool:
  name: 'Default'
  demands:
    - Agent.Name -equals IMGROOT

parameters:
- name: nexla_id
  displayName: Nexla ID
  type: string
  default: '$(NEXLA_SOURCE_ID)'

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      export API_URL=https://dataops.nexla.io/nexla-api
      export API_KEY=19e760802abb425992b3b4481ba051b8
      echo "API_URL is: $API_URL"
      echo "API_KEY is: $API_KEY"
  displayName: "Export and Echo API Variables"
  continueOnError: false

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "Testing exported variables before running Nexla export"
      echo "API_URL: $API_URL"
      echo "API_KEY: $API_KEY"
      nexla flows export --s 53711 -o 53711.json
  displayName: "Run Nexla Export Command"
  continueOnError: false

