trigger:
- main

pool:
  name: 'Default'
  demands:
    - Agent.Name -equals IMGROOT

steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Ensure the correct Python environment is activated
      echo "Checking Python version"
      python --version
      source venv/bin/activate
      pip install nexla-3.2.3-py3-none-any.whl --force
  displayName: 'Install and Venv Activated'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Now run the Nexla command that was failing previously
      echo "Running Nexla command"
      source venv/bin/activate
      nexla --version
      nexla source
  displayName: 'Run Nexla Command'
