trigger:
- main

pool:
  name: 'Default'
  demands:
    - Agent.Name -equals IMGROOT

parameters:
- name: nexla_id
  displayName: Nexla ID
  type: string
  default: '$(NEXLA_SOURCE_ID)'

variables:
  System/Debug: true

steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "Installing wheel file"
      echo $(Build.SourcesDirectory)
      pip install nexla-3.2.3-py3-none-any.whl --break-system-packages
  continueOnError: false

# Step to find and print the installed location of nexla
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Use pip show to find the installation path of nexla
      pip show nexla
  continueOnError: false

# Optional: Add nexla to the PATH if needed
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Assuming nexla is installed in ~/.local/bin or similar
      export PATH=$PATH:\home\groot\.local\bin
      echo "Updated PATH: $PATH"
      nexla --version
  continueOnError: false

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      export API_URL=https://dataops.nexla.io/nexla-api
      export API_KEY=19e760802abb425992b3b4481ba051b8
      echo "API_URL is: $API_URL"
      echo "API_KEY is: $API_KEY"
  continueOnError: false

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'nexla flows export --s 53711 -o 53711.json'
  continueOnError: false
