trigger:
- main

pool:
  name: 'Default'
  demands:
    - Agent.Name -equals IMGROOT


steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: '|
    python -m venv venv
    source venv/bin/activate
    pip install nexla-3.2.3-py3-none-any.whl'
  continueOnError: false
  displayName: 'Installing Nexla CLI'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      export API_URL=https://dataops.nexla.io/nexla-api
      export API_KEY=19e760802abb425992b3b4481ba051b8
      echo "API_URL is: $API_URL"
      echo "API_KEY is: $API_KEY"
  continueOnError: false
  displayName: 'Initalizing the Configuration Parameter'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'nexla env configure --api-key-use-env'
  continueOnError: false
  displayName: 'Configure Nexla CLI (Init Access)'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'nexla flows export --s 53711 -o 53711.json'
  continueOnError: false
  displayName: 'Exporting the Nexla pipeline'