trigger:
- main

pool:
  name: 'Default'
  demands:
    - Agent.Name -equals IMGROOT

steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Ensure the correct Python environment is activated
      echo "Checking Python version"
      python --version

      # Ensure pip is up-to-date
      echo "Updating pip"
      python -m pip install --upgrade pip

      # Install Nexla and required dependencies
      echo "Installing Nexla and dependencies"
      python -m pip install nexla
      python -m pip install beautifultable boto3 requests stdiomask tabulate tenacity validators

      # Verify Nexla installation
      echo "Verifying Nexla installation"
      nexla --help

      # Add Nexla to PATH if it's installed locally
      export PATH=$PATH:/home/groot/.local/bin

      # Verify Nexla command location
      echo "Checking Nexla location"
      which nexla
  displayName: 'Install and Verify Nexla'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Now run the Nexla command that was failing previously
      echo "Running Nexla command"
      nexla --version  # Replace with your actual Nexla command
  displayName: 'Run Nexla Command'
