trigger:
- main

pool:
  name: 'Default'
  demands:
    - Agent.Name -equals IMGROOT

steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Ensure the correct Python environment is activated
      echo "Checking Python version"
      python --version
      nexla source
  displayName: 'Install and Verify Nexla'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Now run the Nexla command that was failing previously
      echo "Running Nexla command"
      nexla --version  # Replace with your actual Nexla command
  displayName: 'Run Nexla Command'
