trigger:
- main

pool:
  name: 'Default'
  demands:
    - Agent.Name -equals IMGROOT

parameters:
- name: nexla_id
  displayName: Nexla ID
  type: string
  default: '$(NEXLA_SOURCE_ID)'

variables:
  System/Debug: true

steps:

# Step to install the Nexla wheel file
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "Installing Nexla Wheel File"
      echo $(Build.SourcesDirectory)
      pip install nexla-3.2.3-py3-none-any.whl --break-system-packages
  displayName: 'Install Nexla Wheel File'
  continueOnError: false

# Step to find and print the installed location of Nexla
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Use pip show to find the installation path of Nexla
      pip show nexla
  displayName: 'Find Nexla Installation Path'
  continueOnError: false

# Step to list all installed Python packages and their locations
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # List installed packages to verify nexla installation
      pip list
  displayName: 'List Installed Python Packages'
  continueOnError: false

# Step to check if Nexla is in the correct location
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Check if nexla is installed and where it is located
      which nexla
  displayName: 'Verify Nexla Installation Location'
  continueOnError: false

# Step to add Nexla to the PATH (adjust for Windows)
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Output PATH to verify Nexla installation directory
      echo "Current PATH: $PATH"
      
      # Ensure the correct path is added to PATH
      if [[ "$OSTYPE" == "linux-gnu"* ]]; then
        export PATH=$PATH:/home/groot/.local/lib/python3.12/site-packages
        export PATH=$PATH:/home/groot/.local/bin/
      else
        # Adjust for Windows Python environment
        export PATH=$PATH:/mnt/c/Users/admin/AppData/Local/Python/Python312/Scripts
      fi
      echo "Updated PATH: $PATH"
  displayName: 'Update PATH for Nexla'
  continueOnError: false

# Step to set API environment variables
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      nexla --version
      export API_URL=https://dataops.nexla.io/nexla-api
      export API_KEY=19e760802abb425992b3b4481ba051b8
      echo "API_URL is: $API_URL"
      echo "API_KEY is: $API_KEY"
      nexla env configure --api-key-use-env
  displayName: 'Set Nexla API Environment Variables'
  continueOnError: false

# Step to run the Nexla command for exporting flows
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'nexla flows export --s 53711 -o 53711.json'
  displayName: 'Export Nexla Flows'
  continueOnError: false
