trigger:
  - main

pool:
  name: 'Default'
  demands:
    - Agent.Name -equals IMGROOT

steps:
# Step 1: Install Nexla CLI
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "Setting up Python environment"
      python -m venv venv
      source venv/bin/activate
      echo "Installing Nexla CLI"
      pip install nexla-3.2.3-py3-none-any.whl
  continueOnError: false
  displayName: 'Installing Nexla CLI'

# Step 2: Initialize Configuration Parameters
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "Exporting API configuration"
      env API_URL=https://dataops.nexla.io/nexla-api API_KEY=19e760802abb425992b3b4481ba051b8 nexla env configure --api-key-use-env
  continueOnError: false
  displayName: 'Initializing and Configure Nexla CLI'

# Step 3: Export Nexla Pipeline
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "Activating virtual environment"
      source venv/bin/activate
      echo "Exporting Nexla pipeline"
      nexla flows export --s 53234 -o 53234.json -a
  continueOnError: false
  displayName: 'Exporting Nexla Pipeline'
