trigger:
- main

pool:
  name: 'Default'
  demands:
    - Agent.Name -equals IMGROOT

parameters:
- name: nexla_id
  displayName: Nexla ID
  type: string
  default: '$(NEXLA_SOURCE_ID)'

steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "Installing wheel file"
      pip install $(Build.SourceDirectory)/nexla-3.2.3-py3-none-any.whl
  displayName: "Install Python Wheel File"
  continueOnError: false


- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      export API_URL=https://dataops.nexla.io/nexla-api
      export API_KEY=19e760802abb425992b3b4481ba051b8
      echo "API_URL is: $API_URL"
      echo "API_KEY is: $API_KEY"
  continueOnError: false

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'nexla flows export --s 53711 -o 53711.json'
  continueOnError: false